@startuml
'https://plantuml.com/sequence-diagram

autonumber


作战资源池 -> 仿真节点 : 发送MQTT消息，通知节点上线注册
仿真节点 --> 作战资源池 : 向资源池发送入云HTTP请求
仿真节点 -> redis : 定时发送节点心跳信息
作战资源池 -> redis : 监听节点心跳，如果心跳失效则将节点注销下线
仿真平台 -> redis : 定时发送节点态势信息
作战云后台 -> redis : 定时获取节点态势信息
作战资源池 -> redis : 定获取节点态势信息
作战云后台 -> 作战资源池 : 通过HTTP请求下发作战任务指令
作战资源池 --> 作战云后台 : 返回作战方案
作战云后台 -> 仿真平台 : 通过HTTP请求向仿真平台下发作战方案

Entity 无人实装平台
作战资源池 -> 无人实装平台 : 定时Ping无人实装平台，检测是否上电
仿真平台 -> 无人实装平台 : 通过UDP向无人实装平台下发指令

database redis

@enduml